import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const migrationsDir = new URL("../supabase/migrations/", import.meta.url);
const migrationsPath = fileURLToPath(migrationsDir);
const migrationName = readdirSync(migrationsDir).find((file) =>
  /create_product_variants_phase1\.sql$/.test(file),
);

const sql = migrationName
  ? readFileSync(join(migrationsPath, migrationName), "utf8")
  : "";

describe("product variants phase 1 migration", () => {
  it("adds explicit legacy inventory model compatibility to products", () => {
    assert.ok(migrationName, "expected a product variants phase 1 migration");
    assert.match(sql, /alter table public\.products\s+add column if not exists inventory_model text/i);
    assert.match(sql, /update public\.products\s+set inventory_model = 'legacy'\s+where inventory_model is null/i);
    assert.match(sql, /alter column inventory_model set default 'legacy'/i);
    assert.match(sql, /alter column inventory_model set not null/i);
    assert.match(sql, /inventory_model in \('legacy', 'variants'\)/i);
  });

  it("creates product_variants with bigint product option references and stock fields", () => {
    assert.match(sql, /create table if not exists public\.product_variants/i);
    assert.match(sql, /id bigint generated by default as identity primary key/i);
    assert.match(sql, /product_id bigint not null/i);
    assert.match(sql, /color_id bigint/i);
    assert.match(sql, /size_id bigint/i);
    assert.match(sql, /price numeric not null/i);
    assert.match(sql, /stock_quantity integer not null default 0/i);
    assert.match(sql, /is_active boolean not null default true/i);
    assert.match(sql, /created_at timestamptz not null default now\(\)/i);
    assert.match(sql, /updated_at timestamptz not null default now\(\)/i);
    assert.doesNotMatch(sql, /timestptz/i);
    assert.match(sql, /check \(price >= 0\)/i);
    assert.match(sql, /check \(stock_quantity >= 0\)/i);
  });

  it("enforces variant color and size rows belong to the same product", () => {
    assert.match(sql, /unique \(id, product_id\)/i);
    assert.match(sql, /foreign key \(color_id, product_id\)\s+references public\.product_colors\(id, product_id\)/i);
    assert.match(sql, /foreign key \(size_id, product_id\)\s+references public\.product_sizes\(id, product_id\)/i);
    assert.match(sql, /references public\.product_colors\(id, product_id\)\s+on update restrict\s+on delete restrict/i);
    assert.match(sql, /references public\.product_sizes\(id, product_id\)\s+on update restrict\s+on delete restrict/i);
    assert.doesNotMatch(sql, /on update cascade/i);
  });

  it("prevents duplicate color, size, color-size, and simple variant combinations", () => {
    assert.match(sql, /product_variants_unique_color_size/i);
    assert.match(sql, /where color_id is not null and size_id is not null/i);
    assert.match(sql, /product_variants_unique_color_only/i);
    assert.match(sql, /where color_id is not null and size_id is null/i);
    assert.match(sql, /product_variants_unique_size_only/i);
    assert.match(sql, /where color_id is null and size_id is not null/i);
    assert.match(sql, /product_variants_unique_simple/i);
    assert.match(sql, /where color_id is null and size_id is null/i);
  });

  it("enforces variant-mode parents and prevents unsafe variants to legacy reversal", () => {
    assert.match(sql, /create or replace function public\.ensure_product_variant_parent_model/i);
    assert.match(sql, /inventory_model <> 'variants'/i);
    assert.match(sql, /create trigger ensure_product_variant_parent_model/i);
    assert.match(sql, /create or replace function public\.prevent_variant_product_legacy_downgrade/i);
    assert.match(sql, /old\.inventory_model = 'variants'/i);
    assert.match(sql, /new\.inventory_model = 'legacy'/i);
    assert.match(sql, /exists \(\s*select 1\s+from public\.product_variants/i);
  });

  it("syncs parent products.price from active variants without touching legacy products", () => {
    assert.match(sql, /create or replace function public\.sync_product_variant_parent_price/i);
    assert.match(sql, /min\(price\)/i);
    assert.match(sql, /where product_id = p_product_id\s+and is_active = true/i);
    assert.match(sql, /where id = p_product_id\s+and inventory_model = 'variants'/i);
    assert.match(sql, /if v_min_price is not null then/i);
    assert.match(sql, /create trigger sync_product_variant_parent_price/i);
  });

  it("serializes parent price sync by locking the product row before reading variants", () => {
    const functionBody = sql.match(
      /create or replace function public\.sync_product_variant_parent_price\([\s\S]*?\nend;\n\$\$;/i,
    )?.[0] || "";
    const lockIndex = functionBody.search(/for update/i);
    const minIndex = functionBody.search(/min\(price\)/i);

    assert.notEqual(lockIndex, -1, "expected parent product row lock");
    assert.notEqual(minIndex, -1, "expected active variant min price query");
    assert.ok(lockIndex < minIndex, "expected parent row lock before min(price)");
    assert.match(functionBody, /if not found then\s+return;\s+end if;/i);
  });

  it("enables public read and admin write RLS without weakening existing tables", () => {
    assert.match(sql, /alter table public\.product_variants enable row level security/i);
    assert.match(sql, /for select\s+to anon, authenticated\s+using \(is_active = true\)/i);
    assert.match(sql, /for all\s+to authenticated\s+using \(public\.is_admin\(\)\)\s+with check \(public\.is_admin\(\)\)/i);
    assert.match(sql, /grant select on public\.product_variants to anon, authenticated/i);
    assert.match(sql, /grant insert, update, delete on public\.product_variants to authenticated/i);
  });

  it("does not change orders, order_items, or generate variants for legacy products", () => {
    assert.doesNotMatch(sql, /alter table public\.order_items/i);
    assert.doesNotMatch(sql, /alter table public\.orders/i);
    assert.doesNotMatch(sql, /insert into public\.product_variants[\s\S]*select/i);
    assert.doesNotMatch(sql, /update public\.product_sizes\s+set\s+in_stock/i);
  });
});
