alter table public.products
  add column if not exists inventory_model text;

update public.products
set inventory_model = 'legacy'
where inventory_model is null;

alter table public.products
  alter column inventory_model set default 'legacy',
  alter column inventory_model set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_inventory_model_check'
      and conrelid = 'public.products'::regclass
  ) then
    alter table public.products
      add constraint products_inventory_model_check
      check (inventory_model in ('legacy', 'variants'));
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'product_colors_id_product_id_unique'
      and conrelid = 'public.product_colors'::regclass
  ) then
    alter table public.product_colors
      add constraint product_colors_id_product_id_unique
      unique (id, product_id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'product_sizes_id_product_id_unique'
      and conrelid = 'public.product_sizes'::regclass
  ) then
    alter table public.product_sizes
      add constraint product_sizes_id_product_id_unique
      unique (id, product_id);
  end if;
end;
$$;

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null
    references public.products(id)
    on delete cascade,
  color_id bigint,
  size_id bigint,
  price numeric not null,
  stock_quantity integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_variants_price_nonnegative
    check (price >= 0),
  constraint product_variants_stock_quantity_nonnegative
    check (stock_quantity >= 0),
  constraint product_variants_color_product_fk
    foreign key (color_id, product_id)
    references public.product_colors(id, product_id)
    on update restrict
    on delete restrict,
  constraint product_variants_size_product_fk
    foreign key (size_id, product_id)
    references public.product_sizes(id, product_id)
    on update restrict
    on delete restrict
);

create unique index if not exists product_variants_unique_color_size
  on public.product_variants (product_id, color_id, size_id)
  where color_id is not null and size_id is not null;

create unique index if not exists product_variants_unique_color_only
  on public.product_variants (product_id, color_id)
  where color_id is not null and size_id is null;

create unique index if not exists product_variants_unique_size_only
  on public.product_variants (product_id, size_id)
  where color_id is null and size_id is not null;

create unique index if not exists product_variants_unique_simple
  on public.product_variants (product_id)
  where color_id is null and size_id is null;

create index if not exists product_variants_product_id_idx
  on public.product_variants (product_id);

create index if not exists product_variants_product_id_is_active_idx
  on public.product_variants (product_id, is_active);

create or replace function public.set_product_variant_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_product_variant_updated_at on public.product_variants;

create trigger set_product_variant_updated_at
  before update on public.product_variants
  for each row
  execute function public.set_product_variant_updated_at();

create or replace function public.ensure_product_variant_parent_model()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inventory_model text;
begin
  select product.inventory_model
    into v_inventory_model
  from public.products product
  where product.id = new.product_id
  for update;

  if not found then
    raise exception 'Product not found.' using errcode = 'P0002';
  end if;

  if v_inventory_model <> 'variants' then
    raise exception 'Product variants can only belong to variant-mode products.' using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists ensure_product_variant_parent_model on public.product_variants;

create trigger ensure_product_variant_parent_model
  before insert or update of product_id on public.product_variants
  for each row
  execute function public.ensure_product_variant_parent_model();

create or replace function public.prevent_variant_product_legacy_downgrade()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.inventory_model = 'variants'
    and new.inventory_model = 'legacy'
    and exists (
      select 1
      from public.product_variants
      where product_id = old.id
      limit 1
    )
  then
    raise exception 'Variant products with variants cannot be switched back to legacy.' using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists prevent_variant_product_legacy_downgrade on public.products;

create trigger prevent_variant_product_legacy_downgrade
  before update of inventory_model on public.products
  for each row
  execute function public.prevent_variant_product_legacy_downgrade();

create or replace function public.sync_product_variant_parent_price(
  p_product_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_min_price numeric;
begin
  perform 1
  from public.products
  where id = p_product_id
  for update;

  if not found then
    return;
  end if;

  select min(price)
    into v_min_price
  from public.product_variants
  where product_id = p_product_id
    and is_active = true;

  if v_min_price is not null then
    update public.products
    set price = v_min_price
    where id = p_product_id
      and inventory_model = 'variants'
      and price is distinct from v_min_price;
  end if;
end;
$$;

create or replace function public.sync_product_variant_parent_price_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.sync_product_variant_parent_price(old.product_id);
    return old;
  end if;

  if tg_op = 'UPDATE' and old.product_id is distinct from new.product_id then
    perform public.sync_product_variant_parent_price(old.product_id);
  end if;

  perform public.sync_product_variant_parent_price(new.product_id);
  return new;
end;
$$;

drop trigger if exists sync_product_variant_parent_price on public.product_variants;

create trigger sync_product_variant_parent_price
  after insert or update of product_id, price, is_active or delete on public.product_variants
  for each row
  execute function public.sync_product_variant_parent_price_trigger();

alter table public.product_variants enable row level security;

create policy "public can read active product variants"
  on public.product_variants
  for select
  to anon, authenticated
  using (is_active = true);

create policy "admins can manage product variants"
  on public.product_variants
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on public.product_variants from anon, authenticated;
grant select on public.product_variants to anon, authenticated;
grant insert, update, delete on public.product_variants to authenticated;
grant usage, select on sequence public.product_variants_id_seq to authenticated;

revoke all on function public.set_product_variant_updated_at() from public;
revoke all on function public.ensure_product_variant_parent_model() from public;
revoke all on function public.prevent_variant_product_legacy_downgrade() from public;
revoke all on function public.sync_product_variant_parent_price(bigint) from public;
revoke all on function public.sync_product_variant_parent_price_trigger() from public;
