alter table public.order_items
  add column if not exists variant_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'order_items_variant_id_fkey'
      and conrelid = 'public.order_items'::regclass
  ) then
    alter table public.order_items
      add constraint order_items_variant_id_fkey
      foreign key (variant_id)
      references public.product_variants(id)
      on delete set null;
  end if;
end $$;

create table if not exists public.variant_inventory_movements (
  id bigint generated by default as identity primary key,
  variant_id bigint references public.product_variants(id) on delete set null,
  order_id uuid references public.orders(id) on delete cascade,
  order_item_id uuid not null,
  quantity_delta integer not null,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint variant_inventory_movements_order_item_id_fkey
    foreign key (order_item_id)
    references public.order_items(id)
    on delete cascade,
  unique (order_item_id, reason)
);

alter table public.variant_inventory_movements enable row level security;

drop policy if exists "Admins can read variant inventory movements" on public.variant_inventory_movements;
create policy "Admins can read variant inventory movements"
  on public.variant_inventory_movements
  for select
  using (public.is_admin() is true);

revoke all on public.variant_inventory_movements from anon, authenticated;
grant select on public.variant_inventory_movements to authenticated;

drop function if exists public.preview_checkout_coupon(text, jsonb);
drop function if exists public.create_checkout_order(uuid, jsonb, jsonb, text);
drop function if exists public.calculate_checkout_coupon_discount(public.coupons, jsonb, uuid);
drop function if exists public.build_checkout_items(jsonb);

create or replace function public.build_checkout_items(p_items jsonb)
returns table (
  product_id bigint,
  variant_id bigint,
  product_name text,
  product_image text,
  product_price numeric,
  color text,
  size text,
  quantity integer,
  category_id bigint,
  line_total numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    product.id as product_id,
    variant.id as variant_id,
    product.title as product_name,
    case
      when variant.id is not null then coalesce(variant_image.image_url, product.cover_image)
      else coalesce(item->>'image', product.cover_image)
    end as product_image,
    case
      when variant.id is not null then variant.price::numeric
      else product.price::numeric
    end as product_price,
    case
      when variant.id is not null then coalesce(variant_color.name, '')
      else coalesce(item->>'color', '')
    end as color,
    case
      when variant.id is not null then coalesce(variant_size.size, '')
      else coalesce(item->>'size', '')
    end as size,
    greatest(coalesce((item->>'quantity')::integer, 0), 0) as quantity,
    product.category_id as category_id,
    round(
      case
        when variant.id is not null then variant.price::numeric
        else product.price::numeric
      end * greatest(coalesce((item->>'quantity')::integer, 0), 0),
      2
    ) as line_total
  from jsonb_array_elements(p_items) item
  join public.products product
    on product.id = (item->>'id')::bigint
  left join public.product_variants variant
    on variant.id = nullif(item->>'variant_id', '')::bigint
   and variant.product_id = product.id
   and variant.is_active = true
  left join public.product_colors variant_color
    on variant_color.id = variant.color_id
   and variant_color.product_id = product.id
  left join public.product_sizes variant_size
    on variant_size.id = variant.size_id
   and variant_size.product_id = product.id
  left join lateral (
    select image.image_url
    from public.product_images image
    where image.color_id = variant.color_id
    order by image.id asc
    limit 1
  ) variant_image on true
  where greatest(coalesce((item->>'quantity')::integer, 0), 0) > 0
    and (
      (nullif(item->>'variant_id', '') is null and coalesce(product.inventory_model, 'legacy') <> 'variants')
      or (
        nullif(item->>'variant_id', '') is not null
        and product.inventory_model = 'variants'
        and variant.id is not null
      )
    )
$$;

create or replace function public.calculate_checkout_coupon_discount(
  p_coupon public.coupons,
  p_items jsonb,
  p_user_id uuid default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_subtotal numeric(12, 2) := 0;
  v_eligible_subtotal numeric(12, 2) := 0;
  v_discount numeric(12, 2) := 0;
  v_total_uses integer := 0;
  v_user_uses integer := 0;
  v_has_product_restrictions boolean := false;
  v_has_category_restrictions boolean := false;
begin
  select coalesce(round(sum(item.line_total), 2), 0)
    into v_subtotal
  from public.build_checkout_items(p_items) item;

  if p_coupon.id is null then
    return jsonb_build_object('ok', false, 'error', 'Coupon not found.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
  end if;

  if p_coupon.active = false then
    return jsonb_build_object('ok', false, 'error', 'Coupon is inactive.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
  end if;

  if p_coupon.starts_at is not null and p_coupon.starts_at > v_now then
    return jsonb_build_object('ok', false, 'error', 'Coupon is not active yet.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
  end if;

  if p_coupon.expires_at is not null and p_coupon.expires_at < v_now then
    return jsonb_build_object('ok', false, 'error', 'Coupon has expired.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
  end if;

  if v_subtotal < p_coupon.minimum_order_amount then
    return jsonb_build_object('ok', false, 'error', 'Minimum order amount not met.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
  end if;

  select count(*) into v_total_uses
  from public.coupon_redemptions
  where coupon_id = p_coupon.id;

  if p_coupon.max_total_uses is not null and v_total_uses >= p_coupon.max_total_uses then
    return jsonb_build_object('ok', false, 'error', 'Coupon usage limit has been reached.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
  end if;

  if p_coupon.max_uses_per_user is not null then
    if p_user_id is null then
      return jsonb_build_object('ok', false, 'error', 'Sign in to use this coupon.', 'requires_authentication', true, 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
    end if;

    select count(*) into v_user_uses
    from public.coupon_redemptions
    where coupon_id = p_coupon.id
      and user_id = p_user_id;

    if v_user_uses >= p_coupon.max_uses_per_user then
      return jsonb_build_object('ok', false, 'error', 'You have already used this coupon.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
    end if;
  end if;

  select exists(select 1 from public.coupon_products where coupon_id = p_coupon.id)
    into v_has_product_restrictions;
  select exists(select 1 from public.coupon_categories where coupon_id = p_coupon.id)
    into v_has_category_restrictions;

  select coalesce(round(sum(item.line_total), 2), 0)
    into v_eligible_subtotal
  from public.build_checkout_items(p_items) item
  where (not v_has_product_restrictions and not v_has_category_restrictions)
    or exists (
      select 1
      from public.coupon_products
      where coupon_id = p_coupon.id
        and product_id = item.product_id
    )
    or exists (
      select 1
      from public.coupon_categories
      where coupon_id = p_coupon.id
        and category_id = item.category_id
    );

  if v_eligible_subtotal <= 0 then
    return jsonb_build_object('ok', false, 'error', 'Coupon does not apply to the items in your cart.', 'discount_amount', 0, 'subtotal', v_subtotal, 'eligible_subtotal', 0, 'total', v_subtotal);
  end if;

  if p_coupon.discount_type = 'percentage' then
    v_discount := round(v_eligible_subtotal * (p_coupon.discount_value / 100), 2);
    if p_coupon.maximum_discount_amount is not null then
      v_discount := least(v_discount, p_coupon.maximum_discount_amount);
    end if;
  elsif p_coupon.discount_type = 'fixed_amount' then
    v_discount := least(p_coupon.discount_value, v_eligible_subtotal);
  else
    return jsonb_build_object('ok', false, 'error', 'Coupon discount type is invalid.', 'discount_amount', 0, 'subtotal', v_subtotal, 'total', v_subtotal);
  end if;

  v_discount := round(least(greatest(v_discount, 0), v_subtotal), 2);

  return jsonb_build_object(
    'ok', true,
    'error', '',
    'coupon_id', p_coupon.id,
    'code', p_coupon.code,
    'discount_amount', v_discount,
    'subtotal', v_subtotal,
    'eligible_subtotal', v_eligible_subtotal,
    'total', round(greatest(v_subtotal - v_discount, 0), 2)
  );
end;
$$;

create or replace function public.preview_checkout_coupon(
  p_code text,
  p_items jsonb
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_coupon public.coupons;
begin
  if p_code is null or btrim(p_code) = '' then
    return jsonb_build_object('ok', false, 'error', 'Enter a coupon code.', 'discount_amount', 0);
  end if;

  select *
    into v_coupon
  from public.coupons
  where upper(btrim(code)) = upper(regexp_replace(btrim(p_code), '\s+', '', 'g'))
  limit 1;

  return public.calculate_checkout_coupon_discount(v_coupon, p_items, auth.uid());
end;
$$;

create or replace function public.create_checkout_order(
  p_order_id uuid,
  p_items jsonb,
  p_customer jsonb,
  p_coupon_code text default null
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_requested_guest boolean := coalesce((p_customer->>'is_guest')::boolean, true);
  v_is_guest boolean := true;
  v_coupon public.coupons;
  v_coupon_result jsonb;
  v_discount numeric(12, 2) := 0;
  v_subtotal numeric(12, 2) := 0;
  v_shipping_cost numeric(12, 2) := 0;
  v_total numeric(12, 2) := 0;
  v_item_count integer := 0;
  v_product_id bigint;
  v_locked_item record;
  v_available_stock integer := 0;
begin
  if p_order_id is null then
    raise exception 'Order id is required.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Cart is empty.';
  end if;

  if p_customer is null or jsonb_typeof(p_customer) <> 'object' then
    raise exception 'Customer details are required.';
  end if;

  if nullif(btrim(p_customer->>'full_name'), '') is null then
    raise exception 'Customer name is required.';
  end if;

  if nullif(btrim(p_customer->>'phone'), '') is null then
    raise exception 'Phone is required.';
  end if;

  if nullif(btrim(p_customer->>'city'), '') is null then
    raise exception 'City is required.';
  end if;

  if nullif(btrim(p_customer->>'address'), '') is null then
    raise exception 'Address is required.';
  end if;

  if v_user_id is not null then
    v_is_guest := false;
  elsif v_requested_guest = false then
    raise exception 'Please login first.';
  else
    v_is_guest := true;
  end if;

  for v_product_id in
    select distinct (item->>'id')::bigint as product_id
    from jsonb_array_elements(p_items) item
    where nullif(item->>'id', '') is not null
    order by product_id
  loop
    perform 1
    from public.products
    where id = v_product_id
    for update;

    if not found then
      raise exception 'One or more cart products or variants could not be found.';
    end if;
  end loop;

  for v_locked_item in
    select
      variant_input.variant_id,
      sum(variant_input.quantity)::integer as requested_quantity
    from (
      select
        nullif(item->>'variant_id', '')::bigint as variant_id,
        greatest(coalesce((item->>'quantity')::integer, 0), 0) as quantity
      from jsonb_array_elements(p_items) item
      where nullif(item->>'variant_id', '') is not null
    ) variant_input
    group by variant_input.variant_id
    order by variant_id
  loop
    select stock_quantity
      into v_available_stock
    from public.product_variants
    where id = v_locked_item.variant_id
      and is_active = true
    for update;

    if not found then
      raise exception 'Selected product option is no longer available.';
    end if;

    if v_available_stock < v_locked_item.requested_quantity then
      raise exception 'Not enough stock for selected product option.';
    end if;
  end loop;

  select count(*), coalesce(round(sum(item.line_total), 2), 0)
    into v_item_count, v_subtotal
  from public.build_checkout_items(p_items) item;

  if v_item_count <> jsonb_array_length(p_items) then
    raise exception 'One or more cart products or variants could not be found.';
  end if;

  if v_subtotal <= 0 then
    raise exception 'Cart total must be greater than zero.';
  end if;

  if p_coupon_code is not null and btrim(p_coupon_code) <> '' then
    select *
      into v_coupon
    from public.coupons
    where upper(btrim(code)) = upper(regexp_replace(btrim(p_coupon_code), '\s+', '', 'g'))
    for update;

    v_coupon_result := public.calculate_checkout_coupon_discount(v_coupon, p_items, v_user_id);

    if coalesce((v_coupon_result->>'ok')::boolean, false) = false then
      raise exception '%', coalesce(v_coupon_result->>'error', 'Coupon is invalid.');
    end if;

    v_discount := (v_coupon_result->>'discount_amount')::numeric;
  end if;

  v_total := round(greatest(v_subtotal - v_discount, 0) + v_shipping_cost, 2);

  -- orders.order_number is IDENTITY BY DEFAULT in the live schema, so it is omitted here.
  insert into public.orders (
    id,
    user_id,
    total_price,
    status,
    payment_method,
    full_name,
    phone,
    city,
    address,
    notes,
    guest_name,
    guest_phone,
    guest_city,
    guest_address,
    guest_notes,
    shipping_cost,
    discount,
    payment_status
  )
  values (
    p_order_id,
    case when v_is_guest then null else v_user_id end,
    v_total,
    'pending',
    'cash',
    case when v_is_guest then null else nullif(btrim(p_customer->>'full_name'), '') end,
    case when v_is_guest then null else nullif(btrim(p_customer->>'phone'), '') end,
    case when v_is_guest then null else nullif(btrim(p_customer->>'city'), '') end,
    case when v_is_guest then null else nullif(btrim(p_customer->>'address'), '') end,
    case when v_is_guest then null else nullif(btrim(p_customer->>'notes'), '') end,
    case when v_is_guest then nullif(btrim(p_customer->>'full_name'), '') else null end,
    case when v_is_guest then nullif(btrim(p_customer->>'phone'), '') else null end,
    case when v_is_guest then nullif(btrim(p_customer->>'city'), '') else null end,
    case when v_is_guest then nullif(btrim(p_customer->>'address'), '') else null end,
    case when v_is_guest then nullif(btrim(p_customer->>'notes'), '') else null end,
    v_shipping_cost,
    v_discount,
    'unpaid'
  );

  insert into public.order_items (
    order_id,
    product_id,
    variant_id,
    product_name,
    product_image,
    product_price,
    color,
    size,
    quantity
  )
  select
    p_order_id,
    item.product_id::text,
    item.variant_id,
    item.product_name,
    item.product_image,
    item.product_price,
    item.color,
    item.size,
    item.quantity
  from public.build_checkout_items(p_items) item;

  for v_locked_item in
    select
      item.variant_id,
      sum(item.quantity)::integer as requested_quantity
    from public.build_checkout_items(p_items) item
    where item.variant_id is not null
    group by item.variant_id
    order by variant_id
  loop
    update public.product_variants
    set stock_quantity = stock_quantity - v_locked_item.requested_quantity
    where id = v_locked_item.variant_id;
  end loop;

  insert into public.variant_inventory_movements (
    variant_id,
    order_id,
    order_item_id,
    quantity_delta,
    reason
  )
  select
    item.variant_id,
    p_order_id,
    item.id,
    -item.quantity,
    'order_created'
  from public.order_items item
  where item.order_id = p_order_id
    and item.variant_id is not null
  on conflict (order_item_id, reason) do nothing;

  if v_coupon.id is not null then
    insert into public.coupon_redemptions (
      coupon_id,
      user_id,
      order_id,
      discount_amount
    )
    values (
      v_coupon.id,
      case when v_is_guest then null else v_user_id end,
      p_order_id,
      v_discount
    );
  end if;

  return jsonb_build_object(
    'id', p_order_id,
    'user_id', case when v_is_guest then null else v_user_id end,
    'total_price', v_total,
    'discount', v_discount,
    'shipping_cost', v_shipping_cost,
    'payment_status', 'unpaid',
    'status', 'pending',
    'coupon_id', v_coupon.id
  );
end;
$$;

create or replace function public.admin_update_order_status(
  p_order_id uuid,
  p_status text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_previous_status text;
  v_item record;
begin
  if public.is_admin() is not true then
    raise exception 'Admin access required.' using errcode = '42501';
  end if;

  if p_order_id is null then
    raise exception 'Order id is required.';
  end if;

  if p_status not in ('pending', 'processing', 'shipped', 'delivered', 'cancelled') then
    raise exception 'Invalid order status.';
  end if;

  select status
    into v_previous_status
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'Order not found.';
  end if;

  if v_previous_status = 'cancelled' and p_status <> 'cancelled' then
    raise exception 'Cancelled orders cannot be reopened.';
  end if;

  update public.orders
  set status = p_status
  where id = p_order_id;

  if p_status = 'cancelled' and coalesce(v_previous_status, '') <> 'cancelled' then
    for v_item in
      select id, variant_id, quantity
      from public.order_items
      where order_id = p_order_id
        and variant_id is not null
      order by variant_id
      for update
    loop
      insert into public.variant_inventory_movements (
        variant_id,
        order_id,
        order_item_id,
        quantity_delta,
        reason
      )
      values (
        v_item.variant_id,
        p_order_id,
        v_item.id,
        v_item.quantity,
        'cancelled'
      )
      on conflict (order_item_id, reason) do nothing;

      if found then
        update public.product_variants
        set stock_quantity = stock_quantity + v_item.quantity
        where id = v_item.variant_id;
      end if;
    end loop;
  end if;

  return jsonb_build_object(
    'id', p_order_id,
    'status', p_status,
    'previous_status', v_previous_status
  );
end;
$$;

revoke all on function public.build_checkout_items(jsonb) from public;
revoke all on function public.calculate_checkout_coupon_discount(public.coupons, jsonb, uuid) from public;
revoke all on function public.preview_checkout_coupon(text, jsonb) from public;
revoke all on function public.create_checkout_order(uuid, jsonb, jsonb, text) from public;
revoke all on function public.admin_update_order_status(uuid, text) from public;
revoke execute on function public.build_checkout_items(jsonb) from anon, authenticated;
revoke execute on function public.calculate_checkout_coupon_discount(public.coupons, jsonb, uuid) from anon, authenticated;
revoke execute on function public.admin_update_order_status(uuid, text) from anon;

grant execute on function public.preview_checkout_coupon(text, jsonb) to anon, authenticated;
grant execute on function public.create_checkout_order(uuid, jsonb, jsonb, text) to anon, authenticated;
grant execute on function public.admin_update_order_status(uuid, text) to authenticated;
